
project_id = "nfkmlwqljkrmottcseyp"

[functions.optimize-image]
verify_jwt = true

[functions.ocr-invoice]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.send-notification]
verify_jwt = true
