
// واجهات تعريف البيانات

// تعريف العملة
interface Currency {
  id: string;
  code: string; // رمز العملة مثل SAR, USD
  name: string;
  symbol: string; // رمز العملة مثل $، ر.س
  isDefault: boolean; // هل هي العملة الافتراضية
  isActive: boolean;
  exchangeRate: number; // سعر الصرف مقابل العملة الافتراضية
  decimalPlaces: number; // عدد الأرقام العشرية
  country?: string; // الدولة (اختياري)
}

// تعريف سعر الصرف
interface ExchangeRate {
  id: string;
  sourceCurrencyId: string; // معرف العملة المصدر
  targetCurrencyId: string; // معرف العملة الهدف
  rate: number; // سعر الصرف
  date: string; // تاريخ سعر الصرف (كسلسلة نصية)
  isManual: boolean; // هل تم إدخاله يدويًا أم تم جلبه تلقائيًا
}

// تعريف الفرع
interface Branch {
  id: string;
  code: string;
  name: string;
  address?: string;
  phone?: string;
  email?: string;
  manager?: string;
  isActive: boolean;
  isMain: boolean;
}

// تعريف نوع القيد
interface VoucherType {
  id: string;
  code: string;
  name: string;
  description?: string;
  isAutoGenerated: boolean; // هل يتم إنشاء القيد تلقائياً عند إجراء معاملة
  isSystem: boolean; // هل هو نوع نظامي لا يمكن تعديله أو حذفه
}

// تعريف طريقة الدفع
interface PaymentMethod {
  id: string;
  code: string;
  name: string;
  description?: string;
  isActive: boolean;
  requiresDetails: boolean; // هل تتطلب تفاصيل إضافية مثل رقم الشيك أو بيانات البطاقة
}

// تعريف مندوب المبيعات
interface SalesRepresentative {
  id: string;
  code: string;
  name: string;
  phone: string;
  email: string;
  commissionRate: number; // نسبة العمولة
  isActive: boolean;
  branchIds: string[]; // الفروع التي يعمل فيها المندوب
}
