
export interface Branch {
  id: string;
  code: string;
  name: string;
  address: string;
  manager: string;
  phone: string;
  email: string;
  isActive: boolean;
  isMainBranch: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Warehouse {
  id: string;
  code: string;
  name: string;
  branchId: string;
  branchName: string;
  type: 'main' | 'sub' | 'external';
  address: string;
  inventoryControl: 'manual' | 'automatic';
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Bank {
  id: string;
  name: string;
  branch: string;
  accountNumber: string;
  accountId: string; // ربط مع شجرة الحسابات
  swiftCode?: string;
  iban?: string;
  currency: string;
  isActive: boolean;
}

export interface Currency {
  id: string;
  code: string; // مثل USD, SAR
  name: string;
  country: string;
  symbol: string;
  isDefault: boolean;
  isActive: boolean;
}

export interface ExchangeRate {
  id: string;
  sourceCurrencyId: string;
  targetCurrencyId: string;
  rate: number;
  date: Date;
  isManual: boolean;
}

export interface AccountingPeriod {
  id: string;
  name: string;
  startDate: Date;
  endDate: Date;
  isClosed: boolean;
  closedDate?: Date;
  fiscalYearId: string;
}

export interface VoucherType {
  id: string;
  code: string;
  name: string;
  description?: string;
  isAutoGenerated: boolean;
  isSystem: boolean;
}

export interface PaymentMethod {
  id: string;
  code: string;
  name: string;
  description?: string;
  isActive: boolean;
  requiresDetails: boolean;
}

export interface SalesRepresentative {
  id: string;
  code: string;
  name: string;
  phone: string;
  email: string;
  commissionRate: number;
  isActive: boolean;
  branchIds: string[]; // الفروع التي يعمل بها
}
