// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfkmlwqljkrmottcseyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ma21sd3FsamtybW90dGNzZXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzg1NTcsImV4cCI6MjA2MjQ1NDU1N30.R0b7rpUeUZNLc_tdVTQ9VBq8X9DoZpBMVwZoaRnOtEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);